# Custom Language File for Launcher Customizer

[ejs.app]
title = "Draco Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/DracoMC-off/Draco-Launcher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "https://www.youtube.com/@DracoMC_off"
mediaDiscordURL = "https://discord.gg/nBanauDRHs"

[ejs.settings]
sourceGithubLink = "https://github.com/DracoMC-off/Draco-Launcher"
supportLink = "https://github.com/DracoMC-off/Draco-Launcher/issues"

[ejs.welcome]
welcomeHeader = "BIENVENUE Sur le Launcher du Draco SMP !!!"
welcomeDescription = ""
welcomeDescCTA = "Vous n'êtes qu'a quelques cliques du Draco SMP."
